### ISSUE TITLE
serviceEnabled return true in Android level 28

### ISSUE THREAD

**Issue by KingWu** [Lyokone/flutterlocation#227]
**Describe the bug**
1) Disable GPS
2) Call serviceEnabled
3) Return true

**Expected behavior**
Return false

**Tested on:**
 - Android, API Level 28. Real device - MI 9

**Comment by AhmedMozaly** [comment]
I face the same behavior, and after checking multiple alternatives seems most of Flutter plugins behave the same way 

To fix this, there are two concepts need to be separated  
* Location Service is Enabled (Android can get location from other services than GPS not sure about IOS)
* GPS Service is Enabled to be more specific on checking GPS is enabled or not

**Comment by AhmedMozaly** [comment]
I think this issue on other project can add more context
https://github.com/BaseflowIT/flutter-permission-handler/issues/85

**Comment by AhmedMozaly** [comment]
Just as an extra note, I just pushed a PR to fix this issue
https://github.com/Lyokone/flutterlocation/pull/229

**Comment by aleksandr-m** [comment]
Seems to be working for me. What do you mean by *Disable GPS*?

You do know that it is an async function and you have to `await` it, right?

**Comment by KingWu** [comment]
@aleksandr-m Just pull down the menu at the Android home page. Then click a 'GPS icon' to turn off it.

**Comment by Mythar** [comment]
This is still an issue, getLocation only returns if device has been set to HIGH.
serviceEnabled always returns true, even when gps has been turned off on device.

**Comment by awhitford** [comment]
Sounds related to #239.

**Comment by Mythar** [comment]
Yes thats it @awhitford, thx for pointing me to that issue.

**Comment by anchliyatushar** [comment]
This package worked like charm 

> https://github.com/alfanhui/new_geolocation
