### ISSUE TITLE
NullPointerException

### ISSUE THREAD

**Issue by otopba** [Lyokone/flutterlocation#472]
**Describe the bug**
I have an exception in my crashlytics:

Caused by java.lang.NullPointerException
Parameter specified as non-null is null: method i.w.d.i.c, parameter activity
com.lyokone.location.FlutterLocationService.checkBackgroundPermissions

```
com.lyokone.location.FlutterLocationService.checkBackgroundPermissions (FlutterLocationService.java)
com.lyokone.location.LocationPlugin.access$000 (LocationPlugin.java)
com.lyokone.location.LocationPlugin.detachActivity (LocationPlugin.java)
com.lyokone.location.LocationPlugin.onDetachedFromActivity (LocationPlugin.java)
io.flutter.embedding.engine.FlutterEngineConnectionRegistry.detachFromActivity (FlutterEngineConnectionRegistry.java)
io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onDetach (FlutterActivityAndFragmentDelegate.java)
io.flutter.embedding.android.FlutterActivity.release (FlutterActivity.java)
io.flutter.embedding.android.FlutterActivity.onDestroy (FlutterActivity.java)
```

Could you fix it please?

**Tested on:**
 - Nexus 5X

**Comment by zarifergashev** [comment]
chichib quyibsizku aka

**Comment by miroslavkudrnac** [comment]
It is fixed in this pull request but there is no new version on pub.dev
https://github.com/Lyokone/flutterlocation/pull/465

**Comment by anshul-arora** [comment]
@miroslavkudrnac  when will be a new version released for this fix ?

**Comment by miroslavkudrnac** [comment]
> @miroslavkudrnac when will be a new version released for this fix ?

I don't know I'm not a maintainer. You can use this lib from source and to pubspec.yaml add 

  location:
    path: dependencies/flutterlocation/location

**Comment by awnigharbia** [comment]
@miroslavkudrnac  I add this code to my pubspec.yaml:

```
location:
    git: 
      url: git://github.com/Lyokone/flutterlocation.git
      ref: master
      path: dependencies/flutterlocation/location
```

but it's not working, Can please help ?

**Comment by awnigharbia** [comment]
The problem is still happing on xiaomi, when I request `getLocation` multiple times.

**Comment by sderungs99** [comment]
I noticed this error in my production app as well, since I upgraded to the new version. Probably time to downgrade again and wait for a new version.

**Comment by henry40408** [comment]
maybe this issue could be closed since 3.2.4 has been released
