### ISSUE TITLE
Crash on app start: java.lang.NullPointerException  java.lang.NullPointerException: Attempt to invoke virtual method 'io.flutter.plugin.common.PluginRegistry$RequestPermissionsResultListener 

### ISSUE THREAD

**Issue by nemoryoliver** [Lyokone/flutterlocation#509]
**Describe the bug**
Crash on app start

**Tested on:**
 - OnePlus 8 Android 11 Real Device

**Additional logs**

``` shell
E/AndroidRuntime(30049): java.lang.RuntimeException: Unable to destroy activity {com.nemorystudios.android.bluer.facebook/com.nemorystudios.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'io.flutter.plugin.common.PluginRegistry$RequestPermissionsResultListener com.lyokone.location.FlutterLocationService.g()' on a null object reference
E/AndroidRuntime(30049): 	at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:5309)
E/AndroidRuntime(30049): 	at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:5339)
E/AndroidRuntime(30049): 	at android.app.ActivityThread.handleRelaunchActivityInner(ActivityThread.java:5631)
E/AndroidRuntime(30049): 	at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:5561)
E/AndroidRuntime(30049): 	at android.app.servertransaction.ActivityRelaunchItem.execute(ActivityRelaunchItem.java:69)
E/AndroidRuntime(30049): 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
E/AndroidRuntime(30049): 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
E/AndroidRuntime(30049): 	at android.app.ClientTransactionHandler.executeTransaction(ClientTransactionHandler.java:58)
E/AndroidRuntime(30049): 	at android.app.ActivityThread.handleRelaunchActivityLocally(ActivityThread.java:5614)
E/AndroidRuntime(30049): 	at android.app.ActivityThread.access$3700(ActivityThread.java:274)
E/AndroidRuntime(30049): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2256)
E/AndroidRuntime(30049): 	at android.os.Handler.dispatchMessage(Handler.java:106)
E/AndroidRuntime(30049): 	at android.os.Looper.loop(Looper.java:233)
E/AndroidRuntime(30049): 	at android.app.ActivityThread.main(ActivityThread.java:8010)
E/AndroidRuntime(30049): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(30049): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:631)
E/AndroidRuntime(30049): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:978)
E/AndroidRuntime(30049): Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'io.flutter.plugin.common.PluginRegistry$RequestPermissionsResultListener com.lyokone.location.FlutterLocationService.g()' on a null object reference
E/AndroidRuntime(30049): 	at com.lyokone.location.b.a(LocationPlugin.java:15)
E/AndroidRuntime(30049): 	at com.lyokone.location.b.b(LocationPlugin.java:1)
E/AndroidRuntime(30049): 	at com.lyokone.location.b.onDetachedFromActivityForConfigChanges(LocationPlugin.java:1)
E/AndroidRuntime(30049): 	at io.flutter.embedding.engine.FlutterEnginePluginRegistry.detachFromActivityForConfigChanges(FlutterEnginePluginRegistry.java:5)
E/AndroidRuntime(30049): 	at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onDetach(FlutterActivityAndFragmentDelegate.java:7)
E/AndroidRuntime(30049): 	at io.flutter.embedding.android.FlutterFragment.onDetach(FlutterFragment.java:2)
E/AndroidRuntime(30049): 	at androidx.fragment.app.Fragment.performDetach(Fragment.java:2)
E/AndroidRuntime(30049): 	at androidx.fragment.app.g.a(FragmentManagerImpl.java:213)
E/AndroidRuntime(30049): 	at androidx.fragment.app.g.l(FragmentManagerImpl.java:9)
E/AndroidRuntime(30049): 	at androidx.fragment.app.g.a(FragmentManagerImpl.java:248)
E/AndroidRuntime(30049): 	at androidx.fragment.app.g.c(FragmentManagerImpl.java:56)
E/AndroidRuntime(30049): 	at androidx.fragment.app.g.d(FragmentManagerImpl.java:15)
E/AndroidRuntime(30049): 	at androidx.fragment.app.d.c(FragmentController.java:1)
E/AndroidRuntime(30049): 	at androidx.fragment.app.FragmentActivity.onDestroy(FragmentActivity.java:2)
E/AndroidRuntime(30049): 	at android.app.Activity.performDestroy(Activity.java:8251)
E/AndroidRuntime(30049): 	at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1364)
E/AndroidRuntime(30049): 	at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:5294)
E/AndroidRuntime(30049): 	... 16 more
Application finished.
Exited (sigterm)

```

**Comment by LaxmikanthMadhyastha** [comment]
Facing this issue on several devices on startup, the app crashes as soon as it is opened with the below message.

```
D/AndroidRuntime(11070): Shutting down VM
E/AndroidRuntime(11070): FATAL EXCEPTION: main
E/AndroidRuntime(11070): Process: com.xyz.app, PID: 11070
E/AndroidRuntime(11070): java.lang.RuntimeException: Unable to destroy activity {com.xyz.app/com.xyz.app.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'io.flutter.plugin.common.PluginRegistry$RequestPermissionsResultListener com.lyokone.location.FlutterLocationService.getServiceRequestPermissionsResultListener()' on a null object reference
E/AndroidRuntime(11070): 	at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:5072)
E/AndroidRuntime(11070): 	at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:5101)
E/AndroidRuntime(11070): 	at android.app.ActivityThread.handleRelaunchActivityInner(ActivityThread.java:5386)
E/AndroidRuntime(11070): 	at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:5318)
E/AndroidRuntime(11070): 	at android.app.servertransaction.ActivityRelaunchItem.execute(ActivityRelaunchItem.java:69)
E/AndroidRuntime(11070): 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
E/AndroidRuntime(11070): 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
E/AndroidRuntime(11070): 	at android.app.ClientTransactionHandler.executeTransaction(ClientTransactionHandler.java:57)
E/AndroidRuntime(11070): 	at android.app.ActivityThread.handleRelaunchActivityLocally(ActivityThread.java:5369)
E/AndroidRuntime(11070): 	at android.app.ActivityThread.access$3800(ActivityThread.java:232)
E/AndroidRuntime(11070): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2133)
E/AndroidRuntime(11070): 	at android.os.Handler.dispatchMessage(Handler.java:107)
E/AndroidRuntime(11070): 	at android.os.Looper.loop(Looper.java:214)
E/AndroidRuntime(11070): 	at android.app.ActivityThread.main(ActivityThread.java:7710)
E/AndroidRuntime(11070): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(11070): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:516)
E/AndroidRuntime(11070): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
E/AndroidRuntime(11070): Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'io.flutter.plugin.common.PluginRegistry$RequestPermissionsResultListener com.lyokone.location.FlutterLocationService.getServiceRequestPermissionsResultListener()' on a null object reference
E/AndroidRuntime(11070): 	at com.lyokone.location.LocationPlugin.deinitialize(LocationPlugin.java:117)
E/AndroidRuntime(11070): 	at com.lyokone.location.LocationPlugin.detachActivity(LocationPlugin.java:56)
E/AndroidRuntime(11070): 	at com.lyokone.location.LocationPlugin.onDetachedFromActivityForConfigChanges(LocationPlugin.java:74)
E/AndroidRuntime(11070): 	at io.flutter.embedding.engine.FlutterEnginePluginRegistry.detachFromActivityForConfigChanges(FlutterEnginePluginRegistry.java:328)
E/AndroidRuntime(11070): 	at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onDetach(FlutterActivityAndFragmentDelegate.java:510)
E/AndroidRuntime(11070): 	at io.flutter.embedding.android.FlutterActivity.onDestroy(FlutterActivity.java:577)
E/AndroidRuntime(11070): 	at android.app.Activity.performDestroy(Activity.java:8078)
E/AndroidRuntime(11070): 	at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1353)
E/AndroidRuntime(11070): 	at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:5057)
E/AndroidRuntime(11070): 	... 16 more


```

**Comment by willroyMyles** [comment]
Anything on this one? happens on every other restart for me

**Comment by maltemedocs** [comment]
If this bug is not fixed we can not continue using this plugin. Please do not mark issues automatically as stale when that includes deal breaking bugs such as this.

What kind of data is needed from our end or the original reporters to continue this investigation?

**Comment by Lyokone** [comment]
Hi, 
Sorry, the stale bot might be a bit agressive, I had not a lot of time to work on the plugin lately.
I've fixed a bunch of error on the 4.2.0 release. Let me know if it fixes it for you :)

**Comment by veresvit** [comment]
Hi, I am facing a similar issue. On Android Emulator API 30 running on Apple Silicon. Oneplus 5 API 29 has no such problems. Can't figure out whether it is an android version problem or the Emulator has an issue. When app requests location after a cold start it crashes with following exception:

```
E/AndroidRuntime( 8857): java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object android.os.Bundle.get(java.lang.String)' on a null object reference
E/AndroidRuntime( 8857): 	at com.lyokone.location.FlutterLocation$2.onLocationResult(FlutterLocation.java:239)
E/AndroidRuntime( 8857): 	at com.google.android.gms.internal.location.zzau.notifyListener(Unknown Source:4)
E/AndroidRuntime( 8857): 	at com.google.android.gms.common.api.internal.ListenerHolder.notifyListenerInternal(Unknown Source:17)
E/AndroidRuntime( 8857): 	at com.google.android.gms.common.api.internal.ListenerHolder$zaa.handleMessage(Unknown Source:5)
E/AndroidRuntime( 8857): 	at android.os.Handler.dispatchMessage(Handler.java:106)
E/AndroidRuntime( 8857): 	at com.google.android.gms.internal.base.zap.dispatchMessage(Unknown Source:8)
E/AndroidRuntime( 8857): 	at android.os.Looper.loop(Looper.java:223)
E/AndroidRuntime( 8857): 	at android.app.ActivityThread.main(ActivityThread.java:7656)
E/AndroidRuntime( 8857): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 8857): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
E/AndroidRuntime( 8857): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
```

When I remove location permissions from settings the app works normally as expected. If i request location permissions again while running the app - the location is found. Cold restart breaks it again.

Thanks for the good work. 👍

**Comment by Lyokone** [comment]
Hi, just released the `4.2.2` to fix this error. Can you check if it's okay for you ?

**Comment by ActivX1** [comment]
> Hi, just released the `4.2.2` to fix this error. Can you check if it's okay for you ?

I think this has fixed the issue. I Was getting in a couple of phones(esp OnePlus 6T, Android 10) till 4.1.1. Now not getting with 4.2.2.

**Comment by veresvit** [comment]
Hi, yes 4.2.2 appears to fix the problem with Emulator on M1 too. Thank you! 👍

**Comment by nemoryoliver** [comment]
On 4.3.0 and got the same crash. Very rare, but still. Tested on physical OnePlus 8 release mode

**Comment by luckycreationsindia** [comment]
Facing this issue on 4.3.0 on Android 11 - OnePlus 7 Pro

**Comment by RogerioDoCarmo** [comment]
I faced the same issue on 4.3.0. For me, the workaround was to use the requestService(); method before any getLocation invocation. I also use these two methods only after I verified the location permission is granted.
I check the permission using permission_handler plugin but I think the issue is the same.

**Comment by kamami** [comment]
Why is this closed? I am also facing this issue with 4.3.0

**Comment by sumit-saurabh** [comment]
We're still facing the issue in 4.3.0

![image](https://user-images.githubusercontent.com/6001355/149455946-90416589-754d-40cb-bb31-5e57e7791f18.png)

**Comment by bertrandgelinas** [comment]
Anyone having this issue using [Flutter Background Geolocation package](https://github.com/transistorsoft/flutter_background_geolocation ) ? I get that same error but i don't use that in my app...

**Comment by sunflowerlabapps** [comment]
I got the same error while running with v4.3.0 on OnePlus 6. Does anyone has fixed this one earlier?

**Comment by xclax** [comment]
I also have this issue on 4.3.0.

**Comment by jackmchristie** [comment]
Same issue for me on 4.3.0

**Comment by BrindaRathodB** [comment]
app still crash for 4.3.0 version

**Comment by limxing** [comment]
app still crash for 4.4.0 version

**Comment by Lyokone** [comment]
Have you tried version 5?

**Comment by bashu-riyan** [comment]
i fixed it by rebooting my mobile.

**Comment by zmeid** [comment]
I had the same issue with `location 4.4.0` on `Pixel 4a Android 13`. Restarting the phone fixed the issue.

**Comment by ch-muhammad-adil** [comment]
Is there any work being done here? I also faced similar issue and looks like there is no work being done at this plugin.

**Comment by real1900** [comment]
same issue here

**Comment by einatguri** [comment]
this is still happening on 4.4.0, why is this issue closed ?

**Comment by wechulimaven** [comment]
AM still facing the same issue`E/AndroidRuntime(12111): java.lang.RuntimeException: Unable to destroy activity {com.towsasa.driver/com.towsasa.driver.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'io.flutter.plugin.common.PluginRegistry$RequestPermissionsResultListener com.lyokone.location.FlutterLocationService.getServiceRequestPermissionsResultListener()' on a null object reference
E/AndroidRuntime(12111): 	at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:5280)
E/AndroidRuntime(12111): 	at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:5311)
E/AndroidRuntime(12111): 	at android.app.ActivityThread.handleRelaunchActivityInner(ActivityThread.java:5646)
E/AndroidRuntime(12111): 	at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:5533)
E/AndroidRuntime(12111): 	at android.app.servertransaction.ActivityRelaunchItem.execute(ActivityRelaunchItem.java:69)
E/AndroidRuntime(12111): 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
E/AndroidRuntime(12111): 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
E/AndroidRuntime(12111): 	at android.app.ClientTransactionHandler.executeTransaction(ClientTransactionHandler.java:58)
E/AndroidRuntime(12111): 	at android.app.ActivityThread.handleRelaunchActivityLocally(ActivityThread.java:5587)
E/AndroidRuntime(12111): 	at android.app.ActivityThread.access$3400(ActivityThread.java:262)
E/AndroidRuntime(12111): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2150)
E/AndroidRuntime(12111): 	at android.os.Handler.dispatchMessage(Handler.java:106)
E/AndroidRuntime(12111): 	at android.os.Looper.loop(Looper.java:268)
E/AndroidRuntime(12111): 	at android.app.ActivityThread.main(ActivityThread.java:8023)
E/AndroidRuntime(12111): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(12111): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:635)
E/AndroidRuntime(12111): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
E/AndroidRuntime(12111): Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'io.flutter.plugin.common.PluginRegistry$RequestPermissionsResultListener com.lyokone.location.FlutterLocationService.getServiceRequestPermissionsResultListener()' on a null obj`

**Comment by sunilkr123** [comment]
i am also facing the same issue

here is my error
Installing build/app/outputs/flutter-apk/app-dev-debug.apk...
W/FlutterActivityAndFragmentDelegate(16124): A splash screen was provided to Flutter, but this is deprecated. See flutter.dev/go/android-splash-migration for migration steps.
E/AndroidRuntime(16124): FATAL EXCEPTION: main
E/AndroidRuntime(16124): Process: uk.co.myperro.app.dev, PID: 16124
E/AndroidRuntime(16124): java.lang.RuntimeException: Unable to destroy activity {uk.co.myperro.app.dev/uk.co.myperro.app.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'io.flutter.plugin.common.PluginRegistry$RequestPermissionsResultListener com.lyokone.location.FlutterLocationService.getServiceRequestPermissionsResultListener()' on a null object reference
E/AndroidRuntime(16124): 	at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:6080)
E/AndroidRuntime(16124): 	at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:6113)
E/AndroidRuntime(16124): 	at android.app.ActivityThread.handleRelaunchActivityInner(ActivityThread.java:6460)
E/AndroidRuntime(16124): 	at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:6341)
E/AndroidRuntime(16124): 	at android.app.servertransaction.ActivityRelaunchItem.execute(ActivityRelaunchItem.java:71)
E/AndroidRuntime(16124): 	at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
E/AndroidRuntime(16124): 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
E/AndroidRuntime(16124): 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
E/AndroidRuntime(16124): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2574)
E/AndroidRuntime(16124): 	at android.os.Handler.dispatchMessage(Handler.java:106)
E/AndroidRuntime(16124): 	at android.os.Looper.loopOnce(Looper.java:226)
E/AndroidRuntime(16124): 	at android.os.Looper.loop(Looper.java:313)
E/AndroidRuntime(16124): 	at android.app.ActivityThread.main(ActivityThread.java:8757)
E/AndroidRuntime(16124): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(16124): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
E/AndroidRuntime(16124): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)
E/AndroidRuntime(16124): Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'io.flutter.plugin.common.PluginRegistry$RequestPermissionsResultListener com.lyokone.location.FlutterLocationService.getServiceRequestPermissionsResultListener()' on a null object reference
E/AndroidRuntime(16124): 	at com.lyokone.location.LocationPlugin.dispose(LocationPlugin.java:117)
E/AndroidRuntime(16124): 	at com.lyokone.location.LocationPlugin.detachActivity(LocationPlugin.java:56)
E/AndroidRuntime(16124): 	at com.lyokone.location.LocationPlugin.onDetachedFromActivityForConfigChanges(LocationPlugin.java:74)
E/AndroidRuntime(16124): 	at io.flutter.embedding.engine.FlutterEngineConnectionRegistry.detachFromActivityForConfigChanges(FlutterEngineConnectionRegistry.java:369)
E/AndroidRuntime(16124): 	at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onDetach(FlutterActivityAndFragmentDelegate.java:747)
E/AndroidRuntime(16124): 	at io.flutter.embedding.android.FlutterActivity.onDestroy(FlutterActivity.java:908)
E/AndroidRuntime(16124): 	at android.app.Activity.performDestroy(Activity.java:8864)
E/AndroidRuntime(16124): 	at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1419)
E/AndroidRuntime(16124): 	at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:6067)
E/AndroidRuntime(16124): 	... 15 more

**Comment by sunilkr123** [comment]
I am also facing the same issues 
can youone suggest how to fix it
here is my error
Installing build/app/outputs/flutter-apk/app-dev-debug.apk...
W/FlutterActivityAndFragmentDelegate(16124): A splash screen was provided to Flutter, but this is deprecated. See flutter.dev/go/android-splash-migration for migration steps.
E/AndroidRuntime(16124): FATAL EXCEPTION: main
E/AndroidRuntime(16124): Process: uk.co.myperro.app.dev, PID: 16124
E/AndroidRuntime(16124): java.lang.RuntimeException: Unable to destroy activity {uk.co.myperro.app.dev/uk.co.myperro.app.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'io.flutter.plugin.common.PluginRegistry$RequestPermissionsResultListener com.lyokone.location.FlutterLocationService.getServiceRequestPermissionsResultListener()' on a null object reference
E/AndroidRuntime(16124): 	at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:6080)
E/AndroidRuntime(16124): 	at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:6113)
E/AndroidRuntime(16124): 	at android.app.ActivityThread.handleRelaunchActivityInner(ActivityThread.java:6460)
E/AndroidRuntime(16124): 	at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:6341)
E/AndroidRuntime(16124): 	at android.app.servertransaction.ActivityRelaunchItem.execute(ActivityRelaunchItem.java:71)
E/AndroidRuntime(16124): 	at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
E/AndroidRuntime(16124): 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
E/AndroidRuntime(16124): 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
E/AndroidRuntime(16124): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2574)
E/AndroidRuntime(16124): 	at android.os.Handler.dispatchMessage(Handler.java:106)
E/AndroidRuntime(16124): 	at android.os.Looper.loopOnce(Looper.java:226)
E/AndroidRuntime(16124): 	at android.os.Looper.loop(Looper.java:313)
E/AndroidRuntime(16124): 	at android.app.ActivityThread.main(ActivityThread.java:8757)
E/AndroidRuntime(16124): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(16124): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
E/AndroidRuntime(16124): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)
E/AndroidRuntime(16124): Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'io.flutter.plugin.common.PluginRegistry$RequestPermissionsResultListener com.lyokone.location.FlutterLocationService.getServiceRequestPermissionsResultListener()' on a null object reference
E/AndroidRuntime(16124): 	at com.lyokone.location.LocationPlugin.dispose(LocationPlugin.java:117)
E/AndroidRuntime(16124): 	at com.lyokone.location.LocationPlugin.detachActivity(LocationPlugin.java:56)
E/AndroidRuntime(16124): 	at com.lyokone.location.LocationPlugin.onDetachedFromActivityForConfigChanges(LocationPlugin.java:74)
E/AndroidRuntime(16124): 	at io.flutter.embedding.engine.FlutterEngineConnectionRegistry.detachFromActivityForConfigChanges(FlutterEngineConnectionRegistry.java:369)
E/AndroidRuntime(16124): 	at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onDetach(FlutterActivityAndFragmentDelegate.java:747)
E/AndroidRuntime(16124): 	at io.flutter.embedding.android.FlutterActivity.onDestroy(FlutterActivity.java:908)
E/AndroidRuntime(16124): 	at android.app.Activity.performDestroy(Activity.java:8864)
E/AndroidRuntime(16124): 	at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1419)
E/AndroidRuntime(16124): 	at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:6067)
E/AndroidRuntime(16124): 	... 15 more

**Comment by xunreal75** [comment]
Could you try location2 package. It's forked and published.
Rename your import to location2

It's a try without warranty.

**Comment by anilkumar416** [comment]
still facing this issue , any solution ?

**Comment by pushpendraKh** [comment]
Is there any repro steps for this crash? We are also getting a lot of crashes reported via firebase.
